spring:
  application:
    name: zuul-test

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/tempsave
      max-file-size: 2048MB
      max-request-size: 2048MB

server:
  port: 9080

ribbon:
  eureka:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: false
  swagger-ui:
    urls[0].name: broker
    urls[0].url: /broker/swagger-ui.json
    path: /swagger-ui.html
    display-request-duration: false
    groups-order: DESC

zuul:
  sensitive-headers:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  routes:
    test-api:
      path: /test/**
      url: http://localhost:6768/test
      strip-prefix: true
    test1-api:
      path: /test1/**
      url: http://localhost:46768/test1
      strip-prefix: true
